version: "3.2"

services:
  tweeter-infra:
    container_name: tweeter-infra
    build: ./
    environment:
      ANSIBLE_CONFIG: /ansible/ansible.cfg
      ANSIBLE_INVENTORY: /ansible/hosts.yaml
    volumes:
      - .:/ansible
      - ~/.ssh:/root/.ssh
    working_dir: /ansible
    # Keep container open
    command: tail -F /ansible/ansible.cfg
