version: "3.2"

services:
  tweeter-infra:
    container_name: tweeter-infra
    image: darrentsung/tweeter-infra:v2
    environment:
      ANSIBLE_CONFIG: /infra/ansible.cfg
    volumes:
      - ./docker/.bashrc:/root/.bashrc
      - .:/infra
      - ~/.ssh:/root/.ssh
    # Keep container open
    command: tail -F /dev/urandom
