version: 2.1

orbs:
  docker: circleci/docker@0.5.19
  dockerize: ganta/dockerize@1.3.2
  persist-env: christeredvartsen/persist-env@0.1.0
  run-with-retry: kimh/run-with-retry@1.0.0

jobs:
  check-healthcheck-on-deployed-instance:
    machine: true
    steps:
      - checkout
      - run: docker-compose up -d
      # Manually inject variables from environment since docker-compose
      # does not inherit environment variables
      - run:
          name: Inject tf variables into file from environment
          command: |
            echo "do_token = \"$TF_VAR_do_token\"" >> ./secrets.auto.tfvars;
            echo "do_ssh_key_name = \"$TF_VAR_do_ssh_key_name\"" >> ./secrets.auto.tfvars;
      - persist-env/set-env-var:
          var-name: WORKSPACE_NAME
          var-value: ci-$CIRCLE_SHA1-$CIRCLE_BUILD_NUM
      # This is not used since we import the ssh_key, but terraform
      # will complain if it is not a valid key.
      - run: ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      # Create infrastructure, run jobs
      - run: |
          docker-compose exec tweeter-infra bash -c "
            source ~/.bashrc;
            terraform workspace new $WORKSPACE_NAME;
            terraform init;
            terraform import digitalocean_ssh_key.main $DO_SSH_KEY_ID;
            terraform apply -auto-approve;"
      # This may fail while waiting for the nomad cluster to bootstrap, so retry.
      - run-with-retry/run-with-retry:
          command: docker-compose exec tweeter-infra bash -c "nomad run jobs/tweeter-backend.nomad;"
          retry-count: 5
          sleep: 2
      - docker/install-dockerize
      # Check that server accepts /healthcheck
      - dockerize/wait-http:
          host: $WORKSPACE_NAME.tweeter.dev
          path: /healthcheck
          # Due to record creation, may not be accessible
          # until around ~20-30 seconds after provisioning.
          timeout: "60s"
      # Always cleanup infrastructure, don't destroy ssh key
      - run:
          command: |
            docker-compose up -d;
            docker-compose exec tweeter-infra bash -c "
              terraform state rm 'digitalocean_ssh_key.main';
              terraform destroy -auto-approve;"
          when: always

workflows:
  version: 2
  build:
    jobs:
      - check-healthcheck-on-deployed-instance
