---
- name: Postgres - Create data volume
  docker_volume:
    name: postgres-{{ item.name }}-data
  loop: "{{ postgres_instances }}"

- name: Postgres - Start container
  docker_container:
    name: "{{ item.name }}"
    image: postgres:11.1
    state: started
    restart: yes
    networks: "{{ item.networks }}"
    volumes:
      - postgres-{{ item.name }}-data:/var/lib/postgresql/data
    ports: "{{ item.port }}:3000"
  loop: "{{ postgres_instances }}"
