---
- name: Start tweeter-backend container
  docker_container:
    name: "{{ item.name }}"
    image: tweetium/tweeter-backend:latest
    state: started
    restart: yes
    ports: "{{ item.port }}:80"
    networks: "{{ item.networks }}"
    env:
      DATABASE_URL: postgresql://postgres:postgres@tweeter-backend-postgres:5432/postgres?sslmode=disable
      # JWT is used for user sessions, this map is defined for JWT rotation.
      JWT_SECRETS_MAP: |
        { "0": "4e054f2e-7436-4525-8fc6-d5801d483697" }
      JWT_SECRETS_CURRENT_KEY: "0"
  loop: "{{ tweeter_backend_instances }}"
