- hosts: all
  vars:
    nomad_debug: true
    nomad_group_name: all
    nomad_node_role: both

  pre_tasks:
    # apt-get update required to find dependencies like cgroup-bin in package lists
    - name: Run 'apt-get update'
      apt:
        update_cache: true

  roles:
    - brianshumate.nomad

  tasks:
    - name: Start nomad
      service: name=nomad state=started enabled=yes
