- hosts: all
  vars:
    # This should match the variables used in setup.yml
    nomad_debug: true
    nomad_group_name: all
    nomad_node_role: both

    # Choose arbitrary IPs here so that nomad will fail to connect.
    # This prevents the snapshot from establishing a quorum, which means
    # that it won't attempt to try to reconnect to the dead server when
    # starting up from an image.
    nomad_bind_address: 9.9.9.9
    nomad_advertise_address: 9.9.9.9

    consul_group_name: all
    consul_node_role: server
    consul_bootstrap_expect: true


  pre_tasks:
    # apt-get update required to find dependencies like cgroup-bin in package lists
    - name: Run 'apt-get update'
      apt:
        update_cache: true

  roles:
    - docker
    - brianshumate.consul
    - brianshumate.nomad
