---
- name: Create docker volumes.
  docker_volume:
    name: "{{ item.name }}"
  loop: "{{ docker_volumes }}"

- name: Start containers.
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    restart: yes
    volumes: "{{ item.volumes | default('[]') }}"
    ports: "{{ item.ports | default('[]') }}"
    networks: "{{ item.networks | default('[]') }}"
    env: "{{ item.env | default('{}') }}"
  loop: "{{ docker_containers }}"
